export const UPDATE_MAIN_STATE = "UPDATE_MAIN_STATE";
export const UPDATE_MODALS_STATE = "UPDATE_MODALS_STATE";
export const UPDATE_GAME_STATE = "UPDATE_GAME_STATE";
export const UPDATE_CREATE_BATTLE_STATE = "UPDATE_CREATE_BATTLE_STATE";
export const UPDATE_CURRENT_BATTLE_STATE = "UPDATE_CURRENT_BATTLE_STATE";
export const UPDATE_BATTLES = "UPDATE_BATTLES";
export const UPDATE_IS_WAITING_ROUND = "UPDATE_IS_WAITING_ROUND";
